# Generated by Django 2.1 on 2019-10-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='PhoneNumber',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
